### ISSUE TITLE
提点建议 🍎

### ISSUE THREAD

**Issue by biezhi** [liuyuyu/chains#1]
1. 缺少配置设计（任何一个框架的项目几乎都需要一套配置体系来维系整个项目中的各种配置读取）
2. `ChainNode` 接口中的 `execute` 方法返回值为 `List<T>` 就限定死了类型，无法做扩展，比如添加其他属性
3. 如果能对 `Jsoup` 做一点封装也许 `IndexNode` 就可以用 `lambda` 表达式完成

**Comment by liuyuyu** [comment]
配置已加。返回值的类型还要考虑考虑才能确定。便利性修改放到后续版本
